### ISSUE TITLE
Open tasks before Release of v1.0

### ISSUE THREAD

**Issue by simlei** [jcryptool/core#219]
This issue lists all recent (2019, 2020) known programming and textual changes in the context of the release of v1.0. Prioritization is as follows:
- **Essential**: If an essential TODO is not done, the release date should be postponed if possible.
- **High Priority**: We really would like to see this in the release of v1.0, but won't postpone the release if something in this group is not done yet.
- **Low Priority**: id.
- **Quick changes**: the estimated time needed to fix this is low enough to not warrant prioritization

There is also a section for things to keep in mind, mostly because they have turned out to be not directly reproducible issues (CNR).

**Comment by simlei** [comment]
#### Essential

- [x] High; ssl transport für Update mechanismus
- [x] L1) ~/Documents internment, "-data" directories
- [x] IDEA/RC6/AES dialog schneidet Elemente ab (Windows problem)
- [x] Substitutionsanalyse Bug [1.2]
- [x] ADFGVX Absturz [4]
- [x] https://github.com/jcryptool/core/issues/225 Absturz Algorithmen / DSA (Keystore-Komplex)

#### High Priority

- [ ] RSA/ElGamal neu programmieren
- [x] [Fill in online help Stumps and missing translations / "Help TODOs" issue](https://github.com/jcryptool/crypto/issues/329)
- [x] Obergrenze für Graph konservativer: Shamir's secret sharing
- [x] Keystore: Neues Problem: alle Schlüsselstärken == 64? bei HMacMD5
- [x] Kontextmenü Keystore->Properties (reproduziert, nur unter Windows)
- [x] Viterbi: Crashes with exit code 133 -- means signal number 5 -- means SIGTRAP (debug related...) in any case: can't handle too big input because of inefficient implementation TODO: Speicherobergrenze: 16GB RAM obergrenze - -Xmx/-Xms `-Xms512M -Xmx4G` oder so bzw. anderen Analyseverfahren
- [x] TaDComposite Hilfe Btn -> Reaktion beim 1. mal, wenn sie schon offen, Highlighten wo hier was passiert - toggle der Kontexthilfe-View + Nachricht in Statuszeile
- [x] Bei Editor Leer und hin- und herwechseln, sind Menüeinträge wie MAC/HMACMD5 nicht richtig enabled/disabled - /org.jcryptool.core/src/org/jcryptool/core/ApplicationWorkbenchAdvisor.java#postStartup() Fixed with https://github.com/jcryptool/core/commit/237498af523f8896401fa401cf478fcac9782fcb by @grthor
- [x] Algorithmen-P. / **McElieceCCA2-Schlüsselerstellung (Keypair)** -- Keylänge auswählen funktioniert nicht -- NoSuchMethodException (std keylength is fine)
- [x] Algorithmen-P. / Schlüssel / Asymmetrisch / McElieceCCA: Eigene Schlüssellänge angeben: Fehler beim Fertigstellen
- [x] Algorithmen-P. / **Hybrid Ciphers \ McEliecePointchevalCipher** -- Trying to encrypt the default text with a default McElieceCCA2 freezes JCT. No exception thrown. Wenn nicht zu beheben, rausnehmen
- [x] Algorithmen-P. / **Signatures \ MeRSA** -- You cant decrypt message, the [key dissapears. log](https://github.com/jcryptool/crypto/files/5414359/log.Mersa_20_10_2020.txt) Wenn nicht zu beheben, rausnehmen
- [x] Algorithmen-P. / **Password-Based Ciphers \ PbeWithSHAAnd3_KeyTripleDES_CBC** -- Nothing happens when you try to click [run button. log](https://github.com/jcryptool/crypto/files/5414352/log.TripleKey_error_20_10_2020.txt) Wenn nicht zu beheben, rausnehmen
- [x] Zahlenhai toolbarbutton s. Kommentar: https://github.com/jcryptool/crypto/issues/237 schließen schnelle Lösung anstreben ansonsten 1.1
- [x] Transpositionsanalyse-Load-Text bleibt hängen bei zB 20MB datei
- [x] Analyse / Viterbi Background Job noch liegen geblieben
- [x] Slideshow-Buttons unter Linux
- [x] Kopal16) Vigenère-Breaker - Graph abgeschnitten bei simple analysis

## Low Priority

- [ ] (Ehemals "High"): Kontextmenü im Hexeditor -> spiegeln der zutreffenden Optionen im "Edit"/"Bearbeiten"-Menü
- [ ] in the online help in the browser, check if the JCrypTool instance has been closed and display a message that the tab may be closed
- [ ] Zum schliessen: #313, Provide means to recall the last command, e.g. via arrow-up-key
- [ ] Mehr Details in "Neuen Schlüssel anlegen"-Display (e.g. HMacMD5)
- [ ] HMAC Key eingeben: `digest = hmac.new("key", "The quick brown fox jumps over the lazy dog").hexdigest()` --> JCT erlaubt es nicht, den Key auch als String (beliebige Länge) einzugeben!
- [ ] workspace-dependent menu language when switching languages (falsche menüsprache bei Language switch -> restart)(Prio: LOW; TODO)
- [ ] [Crypto-Issue: Command line console changes](https://github.com/jcryptool/crypto/issues/313)
- [ ] [Crypto-Issue: Visual plugin: Numbershark GUI changes and fixes](https://github.com/jcryptool/crypto/issues/237)  -- Mail anschauen
- [ ] Homomorphic RSA: Stabilität: Warum ist das Ergebnis negativ? Ich nehme an, weil 112.233.445 * 130.918.078 = 14.693.386.906.718.710  >  N= 536.870.912  ist. Sollte dann nicht besser eine Warnung kommen?
- [ ] *L5)* "Getting to know JCT / first steps" erleichtern
- [ ] Numbershark: Replay-Funktion einer Zahlenfolge
- [ ] Recherche: Onlinehilfe: Drucken einzelner Seiten (iframes) über Ctrl+P / Menü
- [ ] Multivariate Crypto / Rainbow: Wenn man Message ändert, sollte Signature gelöscht werden.
- [x] Introduce "Algorithm perspective" as an entry in the JCT "Algorithms" menu in the default perspective. The idea is to open the algorithms perspective. Hopefully, the rest (show algorithms perspective introduction plugin directly if the user has not seen it yet) falls in place.
- [ ] example editor does not open up again after restart (with or without -de {} change)
- [ ] workspace-dependent menu language when switching languages
- [ ] HMacMD5: Passworteingabe falsch -> nicht direkt Abbruch des Wizards
- [ ] Background Job view (e.g. with Entropy Analysis) opens some times in the middle of the workbench. Reproduce (was it fixed with other perspective improvements?) and if necessary, fix
- [ ] Transposition analysis: (Linux) last transposition column is huge, rest is OK
- [ ] Vigenère breaker: funny text sizes, background is white vs. grey backdrop
- [ ] Vigenère Breaker: When opened at startup: [Log1]
- [ ] Vigenere Breaker: Bug: does not always work on the active editor, but the one that was active on view open
- [ ] Algorithmen-Dialoge: die letzten Einstellungen über eine Session hinweg merken
- [ ] [o] Substitution analysis: no scrollbar
- [ ] [o] Transposition analysis: huge bottom text area with filled table
- [x] [o] Hex-Editor: versteckte rechteste Spalte *in Datei variabler Länge*; auswahl speichern
- [x] Symbole neben Tabs im crypto-explorer
- [x] Core-Issue: Cascades
- [x] FeigeFiatShamir: Angreifer wird zu selten ertappt
- [x] HMacMD5: Neuer Schlüssel anlegen -> wird angezeigt mit icon <Rotes Kreuz> -> ändern in zB Papierkorb-icon
- [x] Vigenère Breaker: Kein smooth scroll
- [x] Vigenère Breaker: Maximiert automatisch
- [x] Direkt nach dem Anlegen eines neuen Texteditor-Reiters (und Text reinpasten), war die Funktion **HMacMD5** nicht verfügbar (ausgegraut). Wechseln zu einem anderem Tab und zurück, dann war es verfügbar.
- [x] Standardperspektive / Algorithmen / zB Hash / zB MD5 + zB SHA-256: HilfeBtn: org.jcryptool.crypto.flexiprovider.integrator
- [x] [Core-Issue: Online help: Rework of the help menu structure / hierarchie](https://github.com/jcryptool/core/issues/206)
- [x] [Core-Issue: Check editor name translations for bugs](https://github.com/jcryptool/core/issues/196)
- [x] [Core-Issue: Test Java 11 JCT on updateability Build](https://github.com/jcryptool/core/issues/166)
- [x] [Crypto-Issue: Test algorithm perspective functionality](https://github.com/jcryptool/crypto/issues/296) *Hinweis beim Pre-release-testing, algo.perspektive zu beachten*
- [x] Introduce "Algorithm perspective" as an entry in the JCT "Algorithms" menu in the default perspective. The idea is to open the algorithms perspective. Hopefully, the rest (show algorithms perspective introduction plugin directly if the user has not seen it yet) falls in place.
- [x] Kryptogra{ph,f} vereinheitlichen → f
- [x] Extended RSA https://github.com/jcryptool/crypto/issues/332

## 1.1 rather than 1.0

- [ ] [Core-Issue: Sign the Mac Release Build](https://github.com/jcryptool/core/issues/205) / make sure Mac Builds work unsigned on all tester's machines
- [ ] Script to export the online help TOC structure as plain text
- [ ] LOW/v1.1: A-Menu\DSA: soll auf Editorbasis laufen
- [ ] Konsistenz des workspace nach Sprachänderung

**Comment by simlei** [comment]
# Low Priority

- [ ] Core-Issue: Online help: Rework of the help menu structure / hierarchie
- [ ] Core-Issue: Check editor name translations for bugs
- [ ] Core-Issue: Test Java 11 JCT on updateability Build LowPriority/ForTheRecord Stability
- [ ] Crypto-Issue: Command line console changes
- [ ] Crypto-Issue: [Hinweis beim Pre-release-testing, algo.perspektive zu beachten] Test algorithm perspective functionality
- [ ] Crypto-Issue: Visual plugin: Numbershark GUI changes and fixes Area:UI+UX-Logic Phase:Backlog Type:Improvement -- Mail anschauen
- [ ] *L5)* "Getting to know JCT / first steps" erleichtern
- [ ] Numbershark: Replay-Funktion einer Zahlenfolge
- [ ] Recherche: Onlinehilfe: Drucken einzelner Seiten (iframes) über Ctrl+P / Menü
- [ ] Symbole neben Tabs im crypto-explorer
- [ ] Core-Issue: Cascades
- [ ] Multivariate Crypto / Rainbow: Wenn man Message ändert, sollte Signature gelöscht werden.

**Comment by simlei** [comment]
# Quick changes

- [x] Introplugin/Algoperspektive Parameter-Dialoge: Geben Sie die hexadezimalen Werte (0-9,A-F) für den Initialisierungsvektor ein. ==> Geben Sie den Initialisierungsvektor in hexadezimaler Form (0-9,A-F) ein. 
- [x] Introplugin/Algoperspektive Parameter-Dialoge: Nach Länge: Bits.  ==>  bit
- [x] Homomorphic RSA: Bleibt noch, dass er (im Dialog Choose parameters") den Wert für d nicht
zurücksetzte, wenn ich oben e zuerst 5 hatte und dann 3 eingab.
- [x] Homomorphic Encryption; Mail 7/12/20 22:39: Layout: In der Zeile mit den Results sollten die Feldbezeichner auf zwei Zeilen verteilt werden. Der links Bezeichner ist abgeschnitten und beide verstehe ich nicht. Was soll ein decryptedN sein?
- [x] Kopal9) SHA-version nicht ersichtlich
- [x] Crypto-Issue: CRT plugin action/toolbar buttons and fixes - data export
- [x] Multivariate Crypto / Rainbow: Noch ein paar Typos in der GUI -- können wir zusammen erledigen.
- [x] 2x "General" / "Allgemein + General" in Preferences
- [x] Leere Preference pages rausnehmen
- [x] https://en.wikipedia.org/w/index.php?title=Bifid_cipher&printable=yes →  printable=yes raus

**Comment by simlei** [comment]
# Could Not Reproduce / keep in mind

- CNR: Grille Verschlüsselung: Kopal6: report that texts with numbers (e.g.?) are not encrypted correctly (numbers appear in wrong places in the ciphertext)
- Kopal16: Vigenère-Breaker: Manual analysis friert ein
- Kopal16: Vigenère Breaker: leeres Fenster

**Comment by simlei** [comment]
Everything prefixed with "Kopal(\d+)" relates to single points from this document: [JCrypTool 1.0.0. Test Kopal 13.07.2020.pdf](https://github.com/jcryptool/core/files/5018022/JCrypTool.1.0.0.Test.Kopal.13.07.2020.pdf)

**Comment by simlei** [comment]
**[1.1]**
![image](https://user-images.githubusercontent.com/982379/90623364-a7c3b400-e216-11ea-8d00-cee567c51b48.png)
**[1.2]**
![image](https://user-images.githubusercontent.com/982379/90623412-b5793980-e216-11ea-80ef-fac3562504b4.png)

**[2]**
```
!ENTRY org.eclipse.ui 4 0 2020-08-12 15:09:20.981
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.ArithmeticException: BigInteger not invertible.
	at java.base/java.math.MutableBigInteger.modInverse(MutableBigInteger.java:2211)
	at java.base/java.math.MutableBigInteger.mutableModInverse(MutableBigInteger.java:2072)
	at java.base/java.math.BigInteger.modInverse(BigInteger.java:3295)
	at java.base/java.math.BigInteger.modPow(BigInteger.java:2783)
	at de.flexiprovider.common.math.FlexiBigInt.modPow(FlexiBigInt.java:106)
	at de.flexiprovider.core.elgamal.ElGamal.messageDecrypt(ElGamal.java:264)
	at de.flexiprovider.api.AsymmetricBlockCipher.doFinal(AsymmetricBlockCipher.java:382)
	at de.flexiprovider.api.Cipher.doFinal(Cipher.java:658)
	at org.jcryptool.crypto.flexiprovider.engines.cipher.AsymmetricBlockCipherEngine.performCipher(AsymmetricBlockCipherEngine.java:102)
	at org.jcryptool.crypto.flexiprovider.engines.cipher.CipherEngine.perform(CipherEngine.java:113)
	at org.jcryptool.crypto.flexiprovider.engines.listener.PerformOperationListener.performOperation(PerformOperationListener.java:33)
	at org.jcryptool.crypto.flexiprovider.operations.engines.PerformOperationManager.firePerformOperation(PerformOperationManager.java:44)
	at org.jcryptool.crypto.flexiprovider.operations.ui.actions.menu.ExecuteOperationHandler.execute(ExecuteOperationHandler.java:42)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:498)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:783)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$3(CommandContributionItem.java:760)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5618)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1405)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4882)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4406)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:633)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jcryptool.core.Application.start(Application.java:50)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
0	of 2816
Somethign went wrong when reading data. Not all data has been read.

**Comment by simlei** [comment]
**[3]** (Shamir's Secret Sharing)
- Im ersten Screenshot mit dem Modulus 1999 fehlt die Linie.
- Im zweiten Screenshot mit dem Modulus 199999 zeigt die Grafik nur
y-Werte bis 650, das ist zu wenig.

![cldicjiilkmdjedg](https://user-images.githubusercontent.com/982379/90623957-84e5cf80-e217-11ea-8c4e-e8b888ea7d5a.png)
![djcdckdoapfifeob](https://user-images.githubusercontent.com/982379/90623959-857e6600-e217-11ea-8b7a-b3719e709190.png)
![fpiladninfhpopih](https://user-images.githubusercontent.com/982379/90623960-8616fc80-e217-11ea-8e9f-951c25b4f06a.png)
![kehgipadnjeiidap](https://user-images.githubusercontent.com/982379/90623961-8616fc80-e217-11ea-8f78-c39932b9b502.png)

**Comment by simlei** [comment]
`[Log1]`
```
## Log1:

!ENTRY org.eclipse.ui.workbench 4 2 2020-09-24 18:00:20.594
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.UnsupportedOperationException: Can't select an item in an empty combo box
	at org.jcryptool.analysis.vigenere.ui.SummaryGui.selectEditorComboItem(SummaryGui.java:295)
	at org.jcryptool.analysis.vigenere.ui.SummaryGui$4.update(SummaryGui.java:196)
	at java.base/java.util.Observable.notifyObservers(Observable.java:173)
	at java.base/java.util.Observable.notifyObservers(Observable.java:129)
	at org.jcryptool.core.operations.editors.EditorsManager.notifyActiveEditorObservers(EditorsManager.java:132)
	at org.jcryptool.core.operations.editors.EditorsManager.checkNeedToNotify(EditorsManager.java:109)
	at org.jcryptool.core.operations.editors.EditorsManager$1.partOpened(EditorsManager.java:366)
	at org.eclipse.ui.internal.WorkbenchPage$12.run(WorkbenchPage.java:5029)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.WorkbenchPage.firePartOpened(WorkbenchPage.java:5026)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.lambda$1(CompatibilityPart.java:122)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5855)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:219)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:132)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.e4.ui.model.application.ui.basic.impl.PartImpl.setObject(PartImpl.java:446)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:133)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:999)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:765)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:736)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:730)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:714)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.lambda$0(PartServiceImpl.java:104)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5855)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:219)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:132)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:170)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:188)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:659)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:623)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:786)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:400)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1262)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3197)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$9(WorkbenchPage.java:3102)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3100)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3070)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3053)
	at org.jcryptool.editor.text.startup.StartUp$1.run(StartUp.java:42)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4988)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4510)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:153)
	at org.jcryptool.core.Application.start(Application.java:50)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by simlei** [comment]
With the release of v1.0.0, this list migrates to the wiki: https://github.com/jcryptool/core/wiki/Improvement-ideas-for-JCT-after-v1.0.0
